development: &default
  mc_api_key: 'd38505dc6ab60151f260a7085456e0a5-us2'
  mc_list_id: '9194888d32'
  s3_bucket: 'tahoe-wedding'
  s3_access_key: '0D6804VEVGREWB054VG2'
  s3_secret: 'ZR5Mzuo5Ye/K2d99EQzmgBMAhXzWrq5Qe0YFOhxC'
  twilio_account_sid: 'AC57966215aa6760ebd15aeaffac4c602f'
  twilio_token: '3e940e1dc0a15f0e2885aa9277157a57'
  twilio_number: '+15304137840'

test: &test
  <<: *default

production:
  <<: *default

